---
name: deploy

on:
  workflow_run:
    branches:
      - main
    types:
      - completed
    workflows:
      - build

run-name: ${{ github.event.workflow_run.display_title }}

jobs:
  release-please:
    permissions:
      contents: write
      issues: write
      pull-requests: write

    runs-on: ubuntu-latest

    steps:
      - id: release
        uses: googleapis/release-please-action@v4
        with:
          release-type: simple

      - if: ${{ steps.release.outputs.release_created }}
        uses: actions/download-artifact@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}

      - if: ${{ steps.release.outputs.release_created }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload ${{ steps.release.outputs.tag_name }} \
            **/*.pdf --clobber
