---
name: Compile PDFs

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container: texlive/texlive:latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Compile PDFs
      run: make
    - name: Upload PDFs
      uses: actions/upload-artifact@v4
      with:
        name: aglorei
        path: aglorei/*.pdf
