---
name: Compile PDFs

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: texlive/texlive:latest
    strategy:
      matrix:
        document:
          - resume
        user:
          - aglorei
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Compile PDFs
      env:
        USER_DIR: ${{ matrix.user }}
      run: make ${{ matrix.document }}.pdf
    - name: Upload PDFs
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.user }}-${{ matrix.document }}
        path: ${{ matrix.user }}/${{ matrix.document }}.pdf
